List<Map> countriesEnglish = [
  {"name": "Afghanistan", "name_ar": "أفغانستان", "dial_code": "+93", "code": "AF"},
  {"name": "Aland Islands", "name_ar": "جزر أولاند", "dial_code": "+358", "code": "AX"},
  {"name": "Albania", "name_ar": "ألبانيا", "dial_code": "+355", "code": "AL"},
  {"name": "Algeria", "name_ar": "الجزائر", "dial_code": "+213", "code": "DZ"},
  {"name": "AmericanSamoa", "name_ar": "ساموا الأمريكية", "dial_code": "+1684", "code": "AS"},
  {"name": "Andorra", "name_ar": "اندورا", "dial_code": "+376", "code": "AD"},
  {"name": "Angola", "name_ar": "أنغولا", "dial_code": "+244", "code": "AO"},
  {"name": "Anguilla", "name_ar": "أنغويلا", "dial_code": "+1264", "code": "AI"},
  {"name": "Antarctica", "name_ar": "أنتاركتيكا", "dial_code": "+672", "code": "AQ"},
  {"name": "Antigua and Barbuda", "name_ar": "أنتيغو وباربودا", "dial_code": "+1268", "code": "AG"},
  {"name": "Argentina", "name_ar": "الأرجنتين", "dial_code": "+54", "code": "AR"},
  {"name": "Armenia", "name_ar": "أرمينا", "dial_code": "+374", "code": "AM"},
  {"name": "Aruba", "name_ar": "اروبا", "dial_code": "+297", "code": "AW"},
  {"name": "Australia", "name_ar": "أستراليا", "dial_code": "+61", "code": "AU"},
  {"name": "Austria", "name_ar": "النمسا", "dial_code": "+43", "code": "AT"},
  {"name": "Azerbaijan", "name_ar": "أذربيجان", "dial_code": "+994", "code": "AZ"},
  {"name": "Bahamas", "name_ar": "الباهاما", "dial_code": "+1242", "code": "BS"},
  {"name": "Bahrain", "name_ar": "البحرين", "dial_code": "+973", "code": "BH"},
  {"name": "Bangladesh", "name_ar": "بنغلاديش", "dial_code": "+880", "code": "BD"},
  {"name": "Barbados", "name_ar": "بربادوس", "dial_code": "+1246", "code": "BB"},
  {"name": "Belarus", "name_ar": "بيلاروسيا", "dial_code": "+375", "code": "BY"},
  {"name": "Belgium", "name_ar": "البلجيك", "dial_code": "+32", "code": "BE"},
  {"name": "Belize", "name_ar": "بيليز", "dial_code": "+501", "code": "BZ"},
  {"name": "Benin", "name_ar": "بينين", "dial_code": "+229", "code": "BJ"},
  {"name": "Bermuda", "name_ar": "برمودا", "dial_code": "+1441", "code": "BM"},
  {"name": "Bhutan", "name_ar": "مملكة بوتان", "dial_code": "+975", "code": "BT"},
  {"name": "Bolivia,Plurinational State of", "name_ar": "بوليفيا", "dial_code": "+591", "code": "BO"},
  {"name": "Bosnia and Herzegovina", "name_ar": "البوسنة والهرسك", "dial_code": "+387", "code": "BA"},
  {"name": "Botswana", "name_ar": "بوتسوانا", "dial_code": "+267", "code": "BW"},
  {"name": "Brazil", "name_ar": "البرازيل", "dial_code": "+55", "code": "BR"},
  {"name": "British Indian Ocean Territory", "name_ar": "اقليم المحيط الهندي البريطاني", "dial_code": "+246", "code": "IO"},
  {"name": "Brunei Darussalam", "name_ar": "بروناي", "dial_code": "+673", "code": "BN"},
  {"name": "Bulgaria", "name_ar": "بلغاريا", "dial_code": "+359", "code": "BG"},
  {"name": "Burkina Faso", "name_ar": "بوركينا فاسو", "dial_code": "+226", "code": "BF"},
  {"name": "Burundi", "name_ar": "بوروندي", "dial_code": "+257", "code": "BI"},
  {"name": "Cambodia", "name_ar": "كمبوديا", "dial_code": "+855", "code": "KH"},
  {"name": "Cameroon", "name_ar": "الكاميرون", "dial_code": "+237", "code": "CM"},
  {"name": "Canada", "name_ar": "كندا", "dial_code": "+1", "code": "CA"},
  {"name": "Cape Verde", "name_ar": "جمهورية الرأس الأخضر", "dial_code": "+238", "code": "CV"},
  {"name": "Cayman Islands", "name_ar": "جزر كايمان", "dial_code": "+ 345", "code": "KY"},
  {"name": "Central African Republic", "name_ar": "جمهورية أفريقيا الوسطى", "dial_code": "+236", "code": "CF"},
  {"name": "Chad", "name_ar": "تشاد", "dial_code": "+235", "code": "TD"},
  {"name": "Chile", "name_ar": "تشيلي", "dial_code": "+56", "code": "CL"},
  {"name": "China", "name_ar": "الصين", "dial_code": "+86", "code": "CN"},
  {"name": "Christmas Island", "name_ar": "جزر كريسماس", "dial_code": "+61", "code": "CX"},
  {"name": "Cocos (Keeling) Islands", "name_ar": "جزر كوكوس", "dial_code": "+61", "code": "CC"},
  {"name": "Colombia", "name_ar": "كولومبيا", "dial_code": "+57", "code": "CO"},
  {"name": "Comoros", "name_ar": "جزر القمر", "dial_code": "+269", "code": "KM"},
  {"name": "Congo", "name_ar": "الكونغو", "dial_code": "+242", "code": "CG"},
  {"name": "Congo, The Democratic Republic of the Congo", "name_ar": "جمهورية الكونغو الديمقراطية", "dial_code": "+243", "code": "CD"},
  {"name": "Cook Islands", "name_ar": "جزر كوك", "dial_code": "+682", "code": "CK"},
  {"name": "Costa Rica", "name_ar": "كوستاريكا", "dial_code": "+506", "code": "CR"},
  {"name": "Cote d'Ivoire", "name_ar": "ساحل العاج", "dial_code": "+225", "code": "CI"},
  {"name": "Croatia", "name_ar": "كرواتيا", "dial_code": "+385", "code": "HR"},
  {"name": "Cuba", "name_ar": "كوبا", "dial_code": "+53", "code": "CU"},
  {"name": "Cyprus", "name_ar": "جزر سيروس", "dial_code": "+357", "code": "CY"},
  {"name": "Czech Republic", "name_ar": "جمهورية التشيك", "dial_code": "+420", "code": "CZ"},
  {"name": "Denmark", "name_ar": "الدنيمارك", "dial_code": "+45", "code": "DK"},
  {"name": "Djibouti", "name_ar": "جيبوتي", "dial_code": "+253", "code": "DJ"},
  {"name": "Dominica", "name_ar": "دومينيكا", "dial_code": "+1767", "code": "DM"},
  {"name": "Dominican Republic", "name_ar": "جمهورية الدومينيكا", "dial_code": "+1849", "code": "DO"},
  {"name": "Ecuador", "name_ar": "الاكوادور", "dial_code": "+593", "code": "EC"},
  {"name": "Egypt", "name_ar": "مصر", "dial_code": "+20", "code": "EG"},
  {"name": "El Salvador", "name_ar": "السيلفادور", "dial_code": "+503", "code": "SV"},
  {"name": "Equatorial Guinea", "name_ar": "غينيا الأستوائية", "dial_code": "+240", "code": "GQ"},
  {"name": "Eritrea", "name_ar": "ارتيريا", "dial_code": "+291", "code": "ER"},
  {"name": "Estonia", "name_ar": "استونيا", "dial_code": "+372", "code": "EE"},
  {"name": "Ethiopia", "name_ar": "اثيوبيا", "dial_code": "+251", "code": "ET"},
  {"name": "Falkland Islands (Malvinas)", "name_ar": "جزر فوكلاند", "dial_code": "+500", "code": "FK"},
  {"name": "Faroe Islands", "name_ar": "جزر فارو", "dial_code": "+298", "code": "FO"},
  {"name": "Fiji", "name_ar": "فيجي", "dial_code": "+679", "code": "FJ"},
  {"name": "Finland", "name_ar": "فيلاندا", "dial_code": "+358", "code": "FI"},
  {"name": "France", "name_ar": "فرنسا", "dial_code": "+33", "code": "FR"},
  {"name": "French Guiana", "name_ar": "غويانا الفرنسية", "dial_code": "+594", "code": "GF"},
  {"name": "French Polynesia", "name_ar": "بولينيزيا الفرنسية", "dial_code": "+689", "code": "PF"},
  {"name": "Gabon", "name_ar": "الغابون", "dial_code": "+241", "code": "GA"},
  {"name": "Gambia", "name_ar": "غامبيا", "dial_code": "+220", "code": "GM"},
  {"name": "Georgia", "name_ar": "جورجيا", "dial_code": "+995", "code": "GE"},
  {"name": "Germany", "name_ar": "المانيا", "dial_code": "+49", "code": "DE"},
  {"name": "Ghana", "name_ar": "غانا", "dial_code": "+233", "code": "GH"},
  {"name": "Gibraltar", "name_ar": "جبل طارق", "dial_code": "+350", "code": "GI"},
  {"name": "Greece", "name_ar": "اليونان", "dial_code": "+30", "code": "GR"},
  {"name": "Greenland", "name_ar": "جرينلاند", "dial_code": "+299", "code": "GL"},
  {"name": "Grenada", "name_ar": "غرينادا", "dial_code": "+1473", "code": "GD"},
  {"name": "Guadeloupe", "name_ar": "غوادلوب", "dial_code": "+590", "code": "GP"},
  {"name": "Guam", "name_ar": "غوام", "dial_code": "+1671", "code": "GU"},
  {"name": "Guatemala", "name_ar": "غواتيمالا", "dial_code": "+502", "code": "GT"},
  {"name": "Guernsey", "name_ar": "غيرنزي", "dial_code": "+44", "code": "GG"},
  {"name": "Guinea", "name_ar": "غينيا", "dial_code": "+224", "code": "GN"},
  {"name": "Guinea-Bissau", "name_ar": "غينيا بيساو", "dial_code": "+245", "code": "GW"},
  {"name": "Guyana", "name_ar": "غيانا", "dial_code": "+595", "code": "GY"},
  {"name": "Haiti", "name_ar": "هايتي", "dial_code": "+509", "code": "HT"},
  {"name": "Holy See (Vatican City State)", "name_ar": "الفاتيكان", "dial_code": "+379", "code": "VA"},
  {"name": "Honduras", "name_ar": "هندوراس", "dial_code": "+504", "code": "HN"},
  {"name": "Hong Kong", "name_ar": "هونغ كونغ", "dial_code": "+852", "code": "HK"},
  {"name": "Hungary", "name_ar": "المجر", "dial_code": "+36", "code": "HU"},
  {"name": "Iceland", "name_ar": "أيسلندا", "dial_code": "+354", "code": "IS"},
  {"name": "India", "name_ar": "الهند", "dial_code": "+91", "code": "IN"},
  {"name": "Indonesia", "name_ar": "أندونيسيا", "dial_code": "+62", "code": "ID"},
  {"name": "Iran, Islamic Republic of Persian Gulf", "name_ar": "ايران", "dial_code": "+98", "code": "IR"},
  {"name": "Iraq", "name_ar": "العراق", "dial_code": "+964", "code": "IQ"},
  {"name": "Ireland", "name_ar": "أيرلندا", "dial_code": "+353", "code": "IE"},
  {"name": "Isle of Man", "name_ar": "جزيرة مان", "dial_code": "+44", "code": "IM"},
  {"name": "Italy", "name_ar": "أيطاليا", "dial_code": "+39", "code": "IT"},
  {"name": "Jamaica", "name_ar": "جاميكا", "dial_code": "+1876", "code": "JM"},
  {"name": "Japan", "name_ar": "اليابان", "dial_code": "+81", "code": "JP"},
  {"name": "Jersey", "name_ar": "جيرسي", "dial_code": "+44", "code": "JE"},
  {"name": "Jordan", "name_ar": "الأردن", "dial_code": "+962", "code": "JO"},
  {"name": "Kazakhstan", "name_ar": "كازخستان", "dial_code": "+77", "code": "KZ"},
  {"name": "Kenya", "name_ar": "كينيا", "dial_code": "+254", "code": "KE"},
  {"name": "Kiribati", "name_ar": "كيريباتي", "dial_code": "+686", "code": "KI"},
  {"name": "Korea, Democratic People's Republic of Korea", "name_ar": "كوريا الشمالية", "dial_code": "+850", "code": "KP"},
  {"name": "Korea, Republic of South Korea", "name_ar": "كوريا الجنوبية", "dial_code": "+82", "code": "KR"},
  {"name": "Kuwait", "name_ar": "الكويت", "dial_code": "+965", "code": "KW"},
  {"name": "Kyrgyzstan", "name_ar": "قيرغيزستان", "dial_code": "+996", "code": "KG"},
  {"name": "Laos", "name_ar": "جمهورية لاوس الديمقراطية الشعبية", "dial_code": "+856", "code": "LA"},
  {"name": "Latvia", "name_ar": "لاتفيا", "dial_code": "+371", "code": "LV"},
  {"name": "Lebanon", "name_ar": "لبنان", "dial_code": "+961", "code": "LB"},
  {"name": "Lesotho", "name_ar": "ليسوثو", "dial_code": "+266", "code": "LS"},
  {"name": "Liberia", "name_ar": "ليبيريا", "dial_code": "+231", "code": "LR"},
  {"name": "Libyan Arab Jamahiriya", "name_ar": "ليبيا", "dial_code": "+218", "code": "LY"},
  {"name": "Liechtenstein", "name_ar": "ليختنشتاين", "dial_code": "+423", "code": "LI"},
  {"name": "Lithuania", "name_ar": "ليتوانيا", "dial_code": "+370", "code": "LT"},
  {"name": "Luxembourg", "name_ar": "لوكسمبورغ", "dial_code": "+352", "code": "LU"},
  {"name": "Macao", "name_ar": "مكاو", "dial_code": "+853", "code": "MO"},
  {"name": "Macedonia", "name_ar": "مقدونيا", "dial_code": "+389", "code": "MK"},
  {"name": "Madagascar", "name_ar": "مدغيشر", "dial_code": "+261", "code": "MG"},
  {"name": "Malawi", "name_ar": "مالاوي", "dial_code": "+265", "code": "MW"},
  {"name": "Malaysia", "name_ar": "ماليزيا", "dial_code": "+60", "code": "MY"},
  {"name": "Maldives", "name_ar": "المالديف", "dial_code": "+960", "code": "MV"},
  {"name": "Mali", "name_ar": "مالي", "dial_code": "+223", "code": "ML"},
  {"name": "Malta", "name_ar": "مالطا", "dial_code": "+356", "code": "MT"},
  {"name": "Marshall Islands", "name_ar": "جزر مارشال", "dial_code": "+692", "code": "MH"},
  {"name": "Martinique", "name_ar": "مارتينيك", "dial_code": "+596", "code": "MQ"},
  {"name": "Mauritania", "name_ar": "موريتانيا العربية", "dial_code": "+222", "code": "MR"},
  {"name": "Mauritius", "name_ar": "موريشيوس", "dial_code": "+230", "code": "MU"},
  {"name": "Mayotte", "name_ar": "مايوت", "dial_code": "+262", "code": "YT"},
  {"name": "Mexico", "name_ar": "المكسيك", "dial_code": "+52", "code": "MX"},
  {"name": "Micronesia, Federated States of Micronesia", "name_ar": "ميكرونيسيا", "dial_code": "+691", "code": "FM"},
  {"name": "Moldova", "name_ar": "مولدوفا", "dial_code": "+373", "code": "MD"},
  {"name": "Monaco", "name_ar": "موناكو", "dial_code": "+377", "code": "MC"},
  {"name": "Mongolia", "name_ar": "منغوليا", "dial_code": "+976", "code": "MN"},
  {"name": "Montenegro", "name_ar": "الجبل الأسود", "dial_code": "+382", "code": "ME"},
  {"name": "Montserrat", "name_ar": "مونتسيرات", "dial_code": "+1664", "code": "MS"},
  {"name": "Morocco", "name_ar": "المغرب", "dial_code": "+212", "code": "MA"},
  {"name": "Mozambique", "name_ar": "موزبيق", "dial_code": "+258", "code": "MZ"},
  {"name": "Myanmar", "name_ar": "ميانمار", "dial_code": "+95", "code": "MM"},
  {"name": "Namibia", "name_ar": "ناميبيا", "dial_code": "+264", "code": "NA"},
  {"name": "Nauru", "name_ar": "جمهورية ناورو", "dial_code": "+674", "code": "NR"},
  {"name": "Nepal", "name_ar": "نيبال", "dial_code": "+977", "code": "NP"},
  {"name": "Netherlands", "name_ar": "هولندا", "dial_code": "+31", "code": "NL"},
  {"name": "Netherlands Antilles", "name_ar": "هولندا", "dial_code": "+599", "code": "AN"},
  {"name": "New Caledonia", "name_ar": "كاليدونيا الجديدة", "dial_code": "+687", "code": "NC"},
  {"name": "New Zealand", "name_ar": "نيوزيلاندا", "dial_code": "+64", "code": "NZ"},
  {"name": "Nicaragua", "name_ar": "نيكاراغوا", "dial_code": "+505", "code": "NI"},
  {"name": "Niger", "name_ar": "النيجر", "dial_code": "+227", "code": "NE"},
  {"name": "Nigeria", "name_ar": "نيجيريا", "dial_code": "+234", "code": "NG"},
  {"name": "Niue", "name_ar": "نييوي", "dial_code": "+683", "code": "NU"},
  {"name": "Norfolk Island", "name_ar": "جزيرة نورفولك", "dial_code": "+672", "code": "NF"},
  {"name": "Northern Mariana Islands", "name_ar": "جزر ماريانا الشمالية", "dial_code": "+1670", "code": "MP"},
  {"name": "Norway", "name_ar": "النرويج", "dial_code": "+47", "code": "NO"},
  {"name": "Oman", "name_ar": "عمان", "dial_code": "+968", "code": "OM"},
  {"name": "Pakistan", "name_ar": "باكستان", "dial_code": "+92", "code": "PK"},
  {"name": "Palau", "name_ar": "جمهورية بالاو", "dial_code": "+680", "code": "PW"},
  {"name": "Palestinian Territory, Occupied", "name_ar": "فلسطين", "dial_code": "+970", "code": "PS"},
  {"name": "Panama", "name_ar": "بنما", "dial_code": "+507", "code": "PA"},
  {"name": "Papua New Guinea", "name_ar": "بابوا غينيا الجديدة", "dial_code": "+675", "code": "PG"},
  {"name": "Paraguay", "name_ar": "باراغوي", "dial_code": "+595", "code": "PY"},
  {"name": "Peru", "name_ar": "بيرو", "dial_code": "+51", "code": "PE"},
  {"name": "Philippines", "name_ar": "الفلبين", "dial_code": "+63", "code": "PH"},
  {"name": "Pitcairn", "name_ar": "جزر بيتكيرن", "dial_code": "+872", "code": "PN"},
  {"name": "Poland", "name_ar": "بولندا", "dial_code": "+48", "code": "PL"},
  {"name": "Portugal", "name_ar": "البرتغال", "dial_code": "+351", "code": "PT"},
  {"name": "Puerto Rico", "name_ar": "بورتوريكو", "dial_code": "+1939", "code": "PR"},
  {"name": "Qatar", "name_ar": "قطر", "dial_code": "+974", "code": "QA"},
  {"name": "Romania", "name_ar": "رومانيا", "dial_code": "+40", "code": "RO"},
  {"name": "Russia", "name_ar": "روسيا", "dial_code": "+7", "code": "RU"},
  {"name": "Rwanda", "name_ar": "رواندا", "dial_code": "+250", "code": "RW"},
  {"name": "Reunion", "name_ar": "لا ريونيون", "dial_code": "+262", "code": "RE"},
  {"name": "Saint Barthelemy", "name_ar": "سان بارتيلمي", "dial_code": "+590", "code": "BL"},
  {"name": "Saint Helena, Ascension and Tristan Da Cunha", "name_ar": "سانت هيلينا", "dial_code": "+290", "code": "SH"},
  {"name": "Saint Kitts and Nevis", "name_ar": "سانت كيتس ونيفس", "dial_code": "+1869", "code": "KN"},
  {"name": "Saint Lucia", "name_ar": "سانت لوسيا", "dial_code": "+1758", "code": "LC"},
  {"name": "Saint Martin", "name_ar": "سانت مارتن", "dial_code": "+590", "code": "MF"},
  {"name": "Saint Pierre and Miquelon", "name_ar": "سان بيير وميكلون", "dial_code": "+508", "code": "PM"},
  {"name": "Saint Vincent and the Grenadines", "name_ar": "سانت فينسنت والغرينادين", "dial_code": "+1784", "code": "VC"},
  {"name": "Samoa", "name_ar": "ساموا الأمريكية", "dial_code": "+685", "code": "WS"},
  {"name": "San Marino", "name_ar": "سان مارينو", "dial_code": "+378", "code": "SM"},
  {"name": "Sao Tome and Principe", "name_ar": "ساو تومي وبرينسيب", "dial_code": "+239", "code": "ST"},
  {"name": "Saudi Arabia", "name_ar": "السعودية", "dial_code": "+966", "code": "SA"},
  {"name": "Senegal", "name_ar": "السينغال", "dial_code": "+221", "code": "SN"},
  {"name": "Serbia", "name_ar": "صربيا", "dial_code": "+381", "code": "RS"},
  {"name": "Seychelles", "name_ar": "جمهورية سيشل", "dial_code": "+248", "code": "SC"},
  {"name": "Sierra Leone", "name_ar": "سيراليون", "dial_code": "+232", "code": "SL"},
  {"name": "Singapore", "name_ar": "سنغافورة", "dial_code": "+65", "code": "SG"},
  {"name": "Slovakia", "name_ar": "سلوفاكيا", "dial_code": "+421", "code": "SK"},
  {"name": "Slovenia", "name_ar": "سلوفينيا", "dial_code": "+386", "code": "SI"},
  {"name": "Solomon Islands", "name_ar": "جزر سليمان", "dial_code": "+677", "code": "SB"},
  {"name": "Somalia", "name_ar": "الصومال", "dial_code": "+252", "code": "SO"},
  {"name": "South Africa", "name_ar": "جنوب أفريقيا", "dial_code": "+27", "code": "ZA"},
  {"name": "South Sudan", "name_ar": "جنوب السودان", "dial_code": "+211", "code": "SS"},
  {"name": "South Georgia and the South Sandwich Islands", "name_ar": "جورجيا الجنوبية وجزر ساندويتش الجنوبية", "dial_code": "+500", "code": "GS"},
  {"name": "Spain", "name_ar": "أسبانيا", "dial_code": "+34", "code": "ES"},
  {"name": "Sri Lanka", "name_ar": "سيريلانكا", "dial_code": "+94", "code": "LK"},
  {"name": "Sudan", "name_ar": "السودان", "dial_code": "+249", "code": "SD"},
  {"name": "Suriname", "name_ar": "جمهورية سورينام", "dial_code": "+597", "code": "SR"},
  {"name": "Svalbard and Jan Mayen", "name_ar": "سفالبارد ويان ماين", "dial_code": "+47", "code": "SJ"},
  {"name": "Swaziland", "name_ar": "سوازيلاند", "dial_code": "+268", "code": "SZ"},
  {"name": "Sweden", "name_ar": "السويد", "dial_code": "+46", "code": "SE"},
  {"name": "Switzerland", "name_ar": "سويسرا", "dial_code": "+41", "code": "CH"},
  {"name": "Syrian Arab Republic", "name_ar": "الجمهورية العربية السورية", "dial_code": "+963", "code": "SY"},
  {"name": "Taiwan", "name_ar": "تايوان", "dial_code": "+886", "code": "TW"},
  {"name": "Tajikistan", "name_ar": "طاجكيستان", "dial_code": "+992", "code": "TJ"},
  {"name": "Tanzania, United Republic of Tanzania", "name_ar": "تنزانيا", "dial_code": "+255", "code": "TZ"},
  {"name": "Thailand", "name_ar": "تايلاند", "dial_code": "+66", "code": "TH"},
  {"name": "Timor-Leste", "name_ar": "تيمور الشرقية", "dial_code": "+670", "code": "TL"},
  {"name": "Togo", "name_ar": "توغو", "dial_code": "+228", "code": "TG"},
  {"name": "Tokelau", "name_ar": "توكيلاو", "dial_code": "+690", "code": "TK"},
  {"name": "Tonga", "name_ar": "مملكة تونغا", "dial_code": "+676", "code": "TO"},
  {"name": "Trinidad and Tobago", "name_ar": "ترينيداد وتوباجو", "dial_code": "+1868", "code": "TT"},
  {"name": "Tunisia", "name_ar": "تونس", "dial_code": "+216", "code": "TN"},
  {"name": "Turkey", "name_ar": "تركيا", "dial_code": "+90", "code": "TR"},
  {"name": "Turkmenistan", "name_ar": "تركمانستان", "dial_code": "+993", "code": "TM"},
  {"name": "Turks and Caicos Islands", "name_ar": "جزر توركس وكايكوس", "dial_code": "+1649", "code": "TC"},
  {"name": "Tuvalu", "name_ar": "توفالو", "dial_code": "+688", "code": "TV"},
  {"name": "Uganda", "name_ar": "أوغندا", "dial_code": "+256", "code": "UG"},
  {"name": "Ukraine", "name_ar": "اكرانيا", "dial_code": "+380", "code": "UA"},
  {"name": "United Arab Emirates", "name_ar": "الأمارات العربية المتحدة", "dial_code": "+971", "code": "AE"},
  {"name": "United Kingdom", "name_ar": "المملكة المتحدة", "dial_code": "+44", "code": "GB"},
  {"name": "United States", "name_ar": "الولايات المتحدة الأمريكية", "dial_code": "+1", "code": "US"},
  {"name": "Uruguay", "name_ar": "الأوروغواي", "dial_code": "+598", "code": "UY"},
  {"name": "Uzbekistan", "name_ar": "اوزباكستان", "dial_code": "+998", "code": "UZ"},
  {"name": "Vanuatu", "name_ar": "فانواتو", "dial_code": "+678", "code": "VU"},
  {"name": "Venezuela,Bolivarian Republic of Venezuela", "name_ar": "فنزويلا", "dial_code": "+58", "code": "VE"},
  {"name": "Vietnam", "name_ar": "فيتنام", "dial_code": "+84", "code": "VN"},
  {"name": "Virgin Islands, British", "name_ar": "جزر العذراء البريطانية", "dial_code": "+1284", "code": "VG"},
  {"name": "Virgin Islands, U.S.", "name_ar": "جزر العذراء الأمريكية", "dial_code": "+1340", "code": "VI"},
  {"name": "Wallis and Futuna", "name_ar": "واليس وفوتونا", "dial_code": "+681", "code": "WF"},
  {"name": "Yemen", "name_ar": "اليمن", "dial_code": "+967", "code": "YE"},
  {"name": "Zambia", "name_ar": "زامبيا", "dial_code": "+260", "code": "ZM"},
  {"name": "Zimbabwe", "name_ar": "زيمبابوي", "dial_code": "+263", "code": "ZW"}
];
